name: undetected-frida

on:
  schedule:
    - cron: "0 9/12 * * *"
  workflow_dispatch:

env:
  FRIDA_VERSION: "16.5.2"

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [arm64]
        os: [android]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Node 18 setup
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: JDK 8 setup
      uses: actions/setup-java@v4
      with:
        java-version: "8"
        distribution: temurin

    - name: Python 3.12 setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: NDK 25c setup (persist env to GITHUB_ENV)
      run: |
        set -euo pipefail

        curl -sSLO https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
        [ "$(sha1sum android-ndk-r25c-linux.zip | awk '{print $1}')" = "53af80a1cce9144025b81c78c8cd556bff42bd0e" ] || (echo "NDK checksum mismatch" && exit 1)
        unzip -qo android-ndk-r25c-linux.zip
        rm -f android-ndk-r25c-linux.zip

        mkdir -p "$HOME/ndk/25.2.9519653"
        rm -rf "$HOME/ndk/25.2.9519653"
        mv android-ndk-r25c "$HOME/ndk/25.2.9519653"
        NDK_DIR="$HOME/ndk/25.2.9519653"

        {
          echo "ANDROID_NDK=$NDK_DIR"
          echo "ANDROID_NDK_ROOT=$NDK_DIR"
          echo "ANDROID_NDK_HOME=$NDK_DIR"
          echo "ANDROID_NDK_LATEST_HOME=$NDK_DIR"
        } >> "$GITHUB_ENV"

    - name: Install build dependencies
      run: |
        set -euo pipefail
        [ "$(id -u)" -eq 0 ] || SUDO=sudo
        ${SUDO} apt-get update
        DEBIAN_FRONTEND=noninteractive ${SUDO} apt-get install -y \
          build-essential ninja-build gcc-multilib g++-multilib lib32stdc++-9-dev \
          flex bison libc6-dev libc6-dev-i386 xz-utils plzip zstd pigz gettext-base
        ${SUDO} /opt/hostedtoolcache/Python/3.12.*/x64/bin/pip3 install -U setuptools lief || true

        _CARCH="${{ matrix.arch }}"
        if [ "${_CARCH%64}" = "${_CARCH}" ]; then
          pushd /opt/hostedtoolcache/Python/3.12.*/x64/include/python3.12 || true
          if [ -f "${{ github.workspace }}/pyconfig.h-i686-x86_64.patch" ]; then
            patch -Rp1 <${{ github.workspace }}/pyconfig.h-i686-x86_64.patch || true
          fi
          popd || true
        fi

    - name: Clone Frida (target version)
      env:
        FRIDA_VERSION: ${{ env.FRIDA_VERSION }}
      run: |
        set -euo pipefail

        if [ ! -d frida ]; then
          git clone --recurse-submodules https://github.com/frida/frida -b "${FRIDA_VERSION}" frida
        else
          echo "frida directory already exists; updating submodules"
          git -C frida fetch --tags --prune || true
          git -C frida submodule update --init --recursive || true
        fi

    - name: Clone frida-stealth (AsenOsen) for patches
      run: |
        set -euo pipefail
        if [ ! -d frida-stealth ]; then
          git clone --depth 1 https://github.com/AsenOsen/frida-stealth.git frida-stealth
        else
          echo "frida-stealth already present"
        fi

    - name: Apply stealth patches (frida-core & frida-gum)
      env:
        FRIDA_VERSION: ${{ env.FRIDA_VERSION }}
      run: |
        set -euo pipefail

        # sanity checks
        test -d frida || (echo "frida not found" && ls -la || true && exit 3)
        test -d frida/frida-core || (echo "frida/frida-core missing" && ls -la frida || true && exit 4)
        test -d frida/frida-gum  || (echo "frida/frida-gum missing"  && ls -la frida || true && exit 5)
        test -f frida-stealth/frida-core/patch.patch || (echo "frida-stealth/frida-core/patch.patch not found" && ls -la frida-stealth || true && exit 6)
        test -f frida-stealth/frida-gum/patch.patch  || (echo "frida-stealth/frida-gum/patch.patch not found" && ls -la frida-stealth || true && exit 7)

        git config --global core.autocrlf false
        git config --global apply.whitespace fix

        echo "Applying frida-core patch"
        pushd frida/frida-core
        # keep .rej files if hunks fail; continue build for inspection
        git apply --reject --whitespace=fix ../../frida-stealth/frida-core/patch.patch || true
        popd

        echo "Applying frida-gum patch"
        pushd frida/frida-gum
        git apply --reject --whitespace=fix ../../frida-stealth/frida-gum/patch.patch || true
        popd

        # collect rejects for inspection
        mkdir -p patch-rejects
        find frida -name "*.rej" -print -exec cp --parents {} patch-rejects/ \; || true

        if [ -n "$(find patch-rejects -type f -name '*.rej' 2>/dev/null)" ]; then
          echo "Some hunks were rejected; .rej files captured in patch-rejects/"
        else
          echo "All patches applied cleanly (no .rej files found)"
        fi

    - name: Build Frida (with patches applied)
      env:
        FRIDA_VERSION: ${{ env.FRIDA_VERSION }}
      run: |
        set -euo pipefail
        echo "ANDROID_NDK_ROOT=${ANDROID_NDK_ROOT}"
        pushd frida

        # Prepare randomized identifiers
        FRIDA_PREFIX="$(tr -cd 'a-z0-9' </dev/urandom | head -c32)"
        SESSION_SERVICE="$(tr -cd 'a-f0-9' </dev/urandom | head -c32)"
        export FRIDA_PREFIX SESSION_SERVICE

        # (Optional) apply any local per-subproject patches as you previously had
        for k in strongR-frida florida rycoh99; do
          [ -d "../${k}" ] || continue
          for i in "../${k}/"*; do
            [ -d "subprojects/${i##*/}" ] || continue
            pushd "subprojects/${i##*/}"
            for j in "../../../${k}/${i##*/}/"*.patch; do
              [ -f "${j}" ] || continue
              FRIDA_PREFIX="${FRIDA_PREFIX}" SESSION_SERVICE="${SESSION_SERVICE}" envsubst <"${j}" | patch -Np1 || true
            done
            popd
          done
        done

        ./configure --prefix="${PWD}/build" \
          --host="${{ matrix.os }}-${{ matrix.arch }}" \
          --enable-frida-tools --enable-gadget --enable-server --enable-portal \
          -- -Dfrida-gum:devkits=gum,gumjs -Dfrida-core:devkits=core

        make -j"$(nproc)"
        popd

    - name: Collect & compress build outputs
      run: |
        set -euo pipefail
        mkdir -p artifacts/${{ matrix.arch }}
        pushd frida

        # server
        if [ -f "build/subprojects/frida-core/server/frida-server" ]; then
          python subprojects/frida-core/src/anti-anti-frida.py build/subprojects/frida-core/server/frida-server || true
          cp build/subprojects/frida-core/server/frida-server ../artifacts/${{ matrix.arch }}/frida-server-${{ matrix.arch }}
        else
          echo "Server binary not found; check build logs"
        fi

        # gadget
        if [ -f "build/subprojects/frida-core/lib/gadget/frida-gadget.so" ]; then
          cp build/subprojects/frida-core/lib/gadget/frida-gadget.so ../artifacts/${{ matrix.arch }}/frida-gadget-${{ matrix.arch }}.so
        else
          echo "Gadget .so not found; check build logs"
        fi

        # devkits/examples (optional)
        for j in $(find build/subprojects -iname '*-example.c' 2>/dev/null || true); do
          _j="${j##*/}"
          _tar="../artifacts/${{ matrix.arch }}/build-${_j%-example.c}-devkit-${FRIDA_VERSION}-${{ matrix.os }}-${{ matrix.arch }}.tar"
          tar -cf "${_tar}" -C "${j%/*}" .
        done
        popd

        # single compressed bundle of artifacts for this matrix cell
        pushd artifacts/${{ matrix.arch }}
        tar -caf ../../undetected-frida-${FRIDA_VERSION}-${{ matrix.os }}-${{ matrix.arch }}.tar.zst .
        popd

    - name: Upload artifacts (build + patch-rejects)
      uses: actions/upload-artifact@v4
      with:
        name: undetected-frida-${{ env.FRIDA_VERSION }}-${{ matrix.os }}-${{ matrix.arch }}
        path: |
          undetected-frida-${{ env.FRIDA_VERSION }}-${{ matrix.os }}-${{ matrix.arch }}.tar.zst
          artifacts/${{ matrix.arch }}/**
          patch-rejects/**
        if-no-files-found: warn
        retention-days: 7
        compression-level: 9
