name: undetected-frida

on:
  schedule:
  - cron: "0 9/12 * * *"
  workflow_dispatch:

env:
  FRIDA_VERSION: "16.5.2"

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [arm64]
        os: [android]

    steps:
    - uses: actions/checkout@v4

    - name: Node 18 setup
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: JDK 8 setup
      uses: actions/setup-java@v4
      with:
        java-version: "8"
        distribution: temurin

    - name: Python 3.12 setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # ---- NDK r25c, persist env so later steps see it ----
    - name: NDK 25c setup
      run: |
        set -e
        curl -sSLO https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
        [ "$(sha1sum android-ndk-r25c-linux.zip | awk '{print $1}')" = "53af80a1cce9144025b81c78c8cd556bff42bd0e" ] || exit 1
        unzip -qo android-ndk-r25c-linux.zip
        rm -f android-ndk-r25c-linux.zip

        # Place it under a canonical r25 path and persist env vars for following steps
        mkdir -p "$HOME/ndk/25.2.9519653"
        rm -rf "$HOME/ndk/25.2.9519653"
        mv android-ndk-r25c "$HOME/ndk/25.2.9519653"
        NDK_DIR="$HOME/ndk/25.2.9519653"

        {
          echo "ANDROID_NDK=$NDK_DIR"
          echo "ANDROID_NDK_ROOT=$NDK_DIR"
          echo "ANDROID_NDK_HOME=$NDK_DIR"
          echo "ANDROID_NDK_LATEST_HOME=$NDK_DIR"
        } >> "$GITHUB_ENV"

    - name: Install dependencies
      run: |
        [ $(id -u) -eq 0 ] || SUDO=sudo
        ${SUDO} apt-get update && DEBIAN_FRONTEND=noninteractive ${SUDO} apt-get install -y \
          build-essential ninja-build gcc-multilib g++-multilib lib32stdc++-9-dev \
          flex bison libc6-dev libc6-dev-i386 xz-utils plzip zstd pigz gettext-base
        ${SUDO} /opt/hostedtoolcache/Python/3.12.*/x64/bin/pip3 install -U setuptools lief

        _CARCH="${{ matrix.arch }}"
        if [ "${_CARCH%64}" = "${_CARCH}" ]; then
          pushd /opt/hostedtoolcache/Python/3.12.*/x64/include/python3.12
          patch -Rp1 <${{ github.workspace }}/pyconfig.h-i686-x86_64.patch || true
          popd
        fi

    - name: Build Frida
      env:
        FRIDA_VERSION: ${{ env.FRIDA_VERSION }}
      run: |
        set -e
        # ANDROID_NDK_* are already in env from the previous step via $GITHUB_ENV
        echo "Using ANDROID_NDK_ROOT=${ANDROID_NDK_ROOT}"

        git clone --recurse-submodules https://github.com/frida/frida -b "${FRIDA_VERSION}"
        pushd frida

        set +e
        FRIDA_PREFIX="$(tr -cd 'a-z0-9' </dev/urandom | head -c32)"
        SESSION_SERVICE="$(tr -cd 'a-f0-9' </dev/urandom | head -c32)"
        set -e

        # Apply local patches if directories exist (no-op otherwise)
        for k in strongR-frida florida rycoh99; do
          [ -d "../${k}" ] || continue
          for i in "../${k}/"*; do
            [ -d "subprojects/${i##*/}" ] || continue
            pushd "subprojects/${i##*/}"
            for j in "../../../${k}/${i##*/}/"*.patch; do
              [ -f "${j}" ] || continue
              FRIDA_PREFIX="${FRIDA_PREFIX}" SESSION_SERVICE="${SESSION_SERVICE}" envsubst <"${j}" | patch -Np1 || true
            done
            popd
          done
        done

        ./configure --prefix="${PWD}/build" \
          --host="${{ matrix.os }}-${{ matrix.arch }}" \
          --enable-frida-tools --enable-gadget --enable-server --enable-portal \
          -- -Dfrida-gum:devkits=gum,gumjs -Dfrida-core:devkits=core

        make -j"$(nproc)"
        popd

    - name: Collect & compress build outputs
      run: |
        set -e
        mkdir -p artifacts/${{ matrix.arch }}
        pushd frida

        # server
        if [ -f "build/subprojects/frida-core/server/frida-server" ]; then
          python subprojects/frida-core/src/anti-anti-frida.py build/subprojects/frida-core/server/frida-server || true
          cp build/subprojects/frida-core/server/frida-server ../artifacts/${{ matrix.arch }}/frida-server-${{ matrix.arch }}
        fi

        # gadget
        if [ -f "build/subprojects/frida-core/lib/gadget/frida-gadget.so" ]; then
          cp build/subprojects/frida-core/lib/gadget/frida-gadget.so ../artifacts/${{ matrix.arch }}/frida-gadget-${{ matrix.arch }}.so
        fi

        # devkits/examples (optional)
        for j in $(find build/subprojects -iname '*-example.c' 2>/dev/null || true); do
          _j="${j##*/}"
          _tar="../artifacts/${{ matrix.arch }}/build-${_j%-example.c}-devkit-${FRIDA_VERSION}-${{ matrix.os }}-${{ matrix.arch }}.tar"
          tar -cf "${_tar}" -C "${j%/*}" .
        done
        popd

        # single compressed bundle
        pushd artifacts/${{ matrix.arch }}
        tar -caf ../../undetected-frida-${FRIDA_VERSION}-${{ matrix.os }}-${{ matrix.arch }}.tar.zst .
        popd

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: undetected-frida-${{ env.FRIDA_VERSION }}-${{ matrix.os }}-${{ matrix.arch }}
        path: |
          undetected-frida-${{ env.FRIDA_VERSION }}-${{ matrix.os }}-${{ matrix.arch }}.tar.zst
          artifacts/${{ matrix.arch }}/**
        if-no-files-found: warn
        retention-days: 7
        compression-level: 9
