name: undetected-frida-build

on:
  schedule:
    - cron: "0 9/12 * * *"
  workflow_dispatch:
    inputs:
      frida_version:
        description: 'Frida version tag to build (e.g. v16.0.0). Use "latest" to build latest release.'
        required: false
        default: 'latest'

env:
  # If you want to restrict which versions can be built from dispatch input,
  # set a comma-separated list here (no spaces). Leave empty to allow any tag.
  ALLOWED_FRIDA_VERSIONS: ""  # e.g. "v16.0.0,v15.2.0,v15.1.6"

jobs:
  check:
    runs-on: ubuntu-22.04
    outputs:
      FRIDA_VERSION: ${{ steps.set.outputs.FRIDA_VERSION }}
    steps:
      - name: Resolve FRIDA_VERSION
        id: set
        run: |
          set -euo pipefail
          INPUT_VERSION="${{ github.event.inputs.frida_version || 'latest' }}"
          ALLOWED="${ALLOWED_FRIDA_VERSIONS:-}"

          if [ -n "$INPUT_VERSION" ] && [ "$INPUT_VERSION" != "latest" ]; then
            # If an allowed list exists, verify membership
            if [ -n "$ALLOWED" ]; then
              IFS=',' read -r -a arr <<< "$ALLOWED"
              ok=0
              for v in "${arr[@]}"; do
                if [ "$v" = "$INPUT_VERSION" ]; then ok=1; break; fi
              done
              if [ "$ok" -ne 1 ]; then
                echo "Dispatch input '$INPUT_VERSION' is not in ALLOWED_FRIDA_VERSIONS ('$ALLOWED')"
                echo "FRIDA_VERSION="
                exit 1
              fi
            fi
            FRIDA_VERSION="$INPUT_VERSION"
          else
            # Fetch latest tag from frida/frida
            frida_version="$(curl -fsSL "https://api.github.com/repos/frida/frida/releases/latest" | jq -r .tag_name)"
            if [ -z "$frida_version" ] || [ "$frida_version" = "null" ]; then
              echo "Failed to determine latest frida release"
              exit 1
            fi
            FRIDA_VERSION="$frida_version"
          fi

          echo "FRIDA_VERSION=${FRIDA_VERSION}" >> "${GITHUB_OUTPUT}"
          echo "Resolved FRIDA_VERSION=${FRIDA_VERSION}"
  build:
    runs-on: ubuntu-22.04
    needs: check
    if: needs.check.outputs.FRIDA_VERSION != ''
    strategy:
      matrix:
        arch: [arm64, arm, x86_64, x86]
        os: [android]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: temurin

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: NDK 25c setup
        run: |
          curl -sSLO https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          # (sha1 check intentionally left — you may change/remove if desired)
          [ "$(sha1sum android-ndk-r25c-linux.zip | awk '{print $1}')" = "53af80a1cce9144025b81c78c8cd556bff42bd0e" ] || exit 1
          unzip -qo android-ndk-r25c-linux.zip; rm android-ndk-r25c-linux.zip;
          rm -rf "${ANDROID_NDK%/*}/25.2.9519653"; mv -v android-ndk-r25c "${ANDROID_NDK%/*}/25.2.9519653"; export ANDROID_NDK="${ANDROID_NDK%/*}/25.2.9519653"
          export ANDROID_NDK_HOME="${ANDROID_NDK}" ANDROID_NDK_ROOT="${ANDROID_NDK}" ANDROID_NDK_LATEST_HOME="${ANDROID_NDK}"

      - name: Install dependencies
        run: |
          [ $(id -u) -eq 0 ] || SUDO=sudo
          ${SUDO} apt-get update && DEBIAN_FRONTEND=noninteractive ${SUDO} apt-get install -y build-essential ninja-build gcc-multilib g++-multilib lib32stdc++-9-dev flex bison libc6-dev libc6-dev-i386 xz-utils plzip zstd pigz gettext-base
          ${SUDO} /opt/hostedtoolcache/Python/3.12.*/x64/bin/pip3 install -U setuptools lief

          _CARCH="${{ matrix.arch }}"; if [ "${_CARCH%64}" = "${_CARCH}" ]; then
            pushd /opt/hostedtoolcache/Python/3.12.*/x64/include/python3.12; patch -Rp1 <${{ github.workspace }}/pyconfig.h-i686-x86_64.patch || true; popd
          fi

      - name: Build Frida
        env:
          ANDROID_NDK: "${{ runner.temp }}/android-ndk"  # not relied on, kept for readability
          FRIDA_VERSION: ${{ needs.check.outputs.FRIDA_VERSION }}
        run: |
          set -euxo pipefail
          # Clone specific tag
          git clone --recurse-submodules https://github.com/frida/frida -b "${FRIDA_VERSION}"
          pushd frida

          # random prefixes used by original script; kept for compatibility
          FRIDA_PREFIX="$(tr -cd 'a-z0-9' </dev/urandom | head -c32)" SESSION_SERVICE="$(tr -cd 'a-f0-9' </dev/urandom | head -c32)"
          export FRIDA_PREFIX SESSION_SERVICE

          # apply local patches if present (keeps original logic but won't fail if none)
          set +e
          for k in strongR-frida florida rycoh99; do
            for i in "../${k}/"*; do
              if [ -d "subprojects/${i##*/}" ]; then
                pushd "subprojects/${i##*/}"
                for j in "../../../${k}/${i##*/}/"*.patch; do
                  if [ -f "${j}" ]; then
                    envsubst <"${j}" | patch -Np1 || true
                  fi
                done
                popd
              fi
            done
          done
          set -e

          # configure & make
          ./configure --prefix="${PWD}/build" --host="${{ matrix.os }}-${{ matrix.arch }}" --enable-frida-tools --enable-gadget --enable-server --enable-portal -- -Dfrida-gum:devkits=gum,gumjs -Dfrida-core:devkits=core
          make -j"$(nproc)"
          popd

      - name: Package artifacts
        env:
          FRIDA_VERSION: ${{ needs.check.outputs.FRIDA_VERSION }}
        run: |
          set -euxo pipefail
          mkdir -p artifacts
          # Gather expected outputs (adjust paths if your build outputs differ)
          if [ -f "frida/build/subprojects/frida-core/server/frida-server" ]; then
            cp frida/build/subprojects/frida-core/server/frida-server "artifacts/frida-server-${{ matrix.arch }}-${FRIDA_VERSION}"
          fi
          if [ -f "frida/build/subprojects/frida-core/lib/gadget/frida-gadget.so" ]; then
            cp frida/build/subprojects/frida-core/lib/gadget/frida-gadget.so "artifacts/frida-gadget-${{ matrix.arch }}-${FRIDA_VERSION}.so"
          fi

          # include devkits / example devkits if present
          find frida/build -maxdepth 2 -type f -name '*-devkit-*.tar' -exec cp {} artifacts/ \; || true

          tar -C artifacts -cvf "frida-artifacts-${{ matrix.arch }}-${FRIDA_VERSION}.tar" .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frida-artifacts-${{ matrix.arch }}
          path: frida-artifacts-*.tar

  assemble:
    runs-on: ubuntu-22.04
    needs: build
    if: needs.check.outputs.FRIDA_VERSION != ''
    steps:
      - name: Download all architecture artifacts
        uses: actions/download-artifact@v4
        with:
          path: frida-artifacts
          # downloads all artifacts uploaded by the matrixed build jobs

      - name: Inspect and create combined archive
        env:
          FRIDA_VERSION: ${{ needs.check.outputs.FRIDA_VERSION }}
        run: |
          set -euxo pipefail
          mkdir -p combined
          cp frida-artifacts/* combined/ || true
          # create a combined zip/tar
          tar -C combined -czf "undetected-frida-all-${FRIDA_VERSION}.tar.gz" .
          # List the packaged file
          ls -l "undetected-frida-all-${FRIDA_VERSION}.tar.gz"

      - name: Upload combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: undetected-frida-all-${{ needs.check.outputs.FRIDA_VERSION }}
          path: undetected-frida-all-*.tar.gz
